### PR TITLE
systemd: Rename StartLimitInterval to StartLimitIntervalSec

### LINKED ISSUE #69: Old setting name in systemd service file
The `StartLimitInterval` setting [was renamed](https://github.com/systemd/systemd/commit/f0367da7d1a61ad698a55d17b5c28ddce0dc265a) to `StartLimitIntervalSec` in systemd-230.

### PR DESCRIPTION
**Pull request by Flowdalic**
Fixes #69.

### CODE REVIEW

**Comment by phillipberndt** [comment]
Ubuntu LTS still uses systemd-229.

**Comment by Flowdalic** [comment]
> Ubuntu LTS still uses systemd-229.

Ahh, ok, so you want to wait until Ubuntu 18.04 for this? It's your choice, but I would let autorandr Ubuntu package maintainer (if one comes up) take care of that.

**Comment by phillipberndt** [comment]
See #69: This package has Ubuntu LTS users. So merging this would do harm. To come back to my original question: Things aren't actually broken without this PR, aren't they?

I would even wait 2-3 months until after the next LTS release to give the forks time to catch up. End of June next year sounds like a good time to merge this, Mint 19 should come out around that time.

That is, *unless* something makes this PR more urgent: If for example some distribution decided to drop the legacy code from systemd I'll be happy to merge this earlier, even without maintaining compatibility with old systems if there's no way around it.

**Comment by Flowdalic** [comment]
> To come back to my original question: Things aren't actually broken without this PR, aren't they?

No, I wasn't aware that newer systemd versions still accept the old key. :)

**Comment by phillipberndt** [comment]
Ok, then let's postpone this until next year!

**Pull request closed without merging**
