### PR TITLE
Add --match-edid option to match profiles based on edid

### PR DESCRIPTION
**Pull request by spiriou**
In some cases the display names change so the profile matching fails.
This commit introduces the "--match-edid" option, that allows one to
specify that the profiles matching should be done based on display edid.

This is done by updating the profiles after loading, based on current
display name/edid mapping requested using xrandr.

### CODE REVIEW

**Comment by phillipberndt** [comment]
I distinctly remember we discussed some changes offline :thinking: Anyway, I forgot, it seems you did, too, so I'll merge as is before I entirely forget about this..

Thanks again for contributing!

**Comment by Tchekda** [comment]
I don't really understand how this feature works. 
If i already have some generated config files, will if work ? And will it correctly use the right output name in the xrandr command?

**Comment by spiriou** [comment]
> I don't really understand how this feature works. If i already have some generated config files, will if work ? And will it correctly use the right output name in the xrandr command?

@Tchekda yes and yes.
The `--match-edid` option is supposed to rearrange config after it is loaded from file. The output name that is used in the xrandr command is overwritten based on the display `edid` so it should work with existing generated config files.

**Comment by Tchekda** [comment]
Awesome, thank you. 
Will be waiting for the next release to have it available on NixOS or will try to build it on my own.

**Comment by Tchekda** [comment]
I just tested It, it works perfectly ! You are such a god for implementing this feature !!

**Comment by axolx** [comment]
I just discovered this very useful flag.  Thank you!

In case it helps others, this is how I added the `--match-edid` flag to the autorandr systemd service for Arch:

Edit the systemd unit file that ships [the Arch autorandr package](https://archlinux.org/packages/extra/any/autorandr/):

```bash
sudo systemctl edit autorandr.service
```
Override the ExecStart directive with this content (See [Arch / systemd / Editing provided units / Examples](https://wiki.archlinux.org/title/Systemd#Replacement_unit_files)):

```
[Service]
ExecStart=
ExecStart=/usr/bin/autorandr --match-edid --batch --change --default default
```

Reload the daemon to apply changes:

```
systemctl daemon-reload
```

**Pull request merged**
